# APP DEPLOYMENT
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-kub-16
  name: my-kub-16
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-kub-16-exposed
  template:
    metadata:
      labels:
        run: my-kub-16-exposed
    spec:
      containers:
      - name: my-app-1
        image: localhost:5000/my-app-1:0.1.3
        ports:
        - containerPort: 80
          protocol: TCP
      - name: my-app-2
        image: localhost:5000/my-app-2:0.1.3
        ports:
        - containerPort: 8003
          protocol: TCP


# APP SERVICE
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-kub-16
  name: my-kub-16
spec:
  ports:
  - port: 80
    protocol: TCP
    name: my-app-1
    targetPort: 80
  - port: 8003
    protocol: TCP
    name: my-app-2
    targetPort: 8003
  # - name: my-app-1
  #   protocol: TCP
  #   port: 80
  #   targetPort: 80
  # - name: my-app-2
  #   protocol: TCP
  #   port: 8003
  #   targetPort: 8003
  selector:
    run: my-kub-16-exposed
  type: NodePort