# APP DEPLOYMENT
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-kub-with-mongo
  name: my-kub-with-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-kub-with-mongo-exposed
  template:
    metadata:
      labels:
        run: my-kub-with-mongo-exposed
    spec:
      containers:
      - name: my-app-1
        image: localhost:5000/my-app-1:0.1.3
        ports:
        - containerPort: 80
          protocol: TCP
      - name: my-app-2
        image: localhost:5000/my-app-2:0.1.3
        ports:
        - containerPort: 8003
          protocol: TCP
      - name: my-app-3
        image: mongo
        ports:
        - containerPort: 27017


# APP SERVICE
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-kub-with-mongo
  name: my-kub-with-mongo
spec:
  ports:
  - port: 80
    protocol: TCP
    name: my-app-1
    targetPort: 80
  - port: 8003
    protocol: TCP
    name: my-app-2
    targetPort: 8003
  - port: 27017
    name: my-app-3
    targetPort: 27017
  selector:
    run: my-kub-with-mongo-exposed
  type: NodePort